version: '3.8'
services:
  mongodb:
    image: 'mongo'
    networks:
      - backend

  backend:
    build: ./Server
    env_file: ./Server/.env
    ports:
      - "4444:4444"
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend


  frontend:
    build: ./Client
    env_file: ./Client/.env
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backendd
    networks:
      - backend
      - frontend
networks:
  backend:
  frontend:
